### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jacobg** [transistorsoft/transistor-background-fetch#11]
My mobile app is getting a NullPointerException on the following line of code:
https://github.com/transistorsoft/transistor-background-fetch/blob/997647b94ee2ae4ecbdb475be2cb3f892b1746cd/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BackgroundFetchConfig.java#L342

The full exception message is:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at com.transistorsoft.tsbackgroundfetch.BackgroundFetchConfig$1.run(BackgroundFetchConfig.java:342)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

I am not using this library directly, but rather as a transitive dependency of `cordova-background-geolocation` version 3.9.4. I also don't think I'm using background fetch for anything, e.g., accessing a data backend through transistorsoft. It's merely in-memory event listeners for geo location position.

Here is a screenshot of the Crashlytics message:

<img width="1263" alt="Screen Shot 2020-12-09 at 10 12 35 AM" src="https://user-images.githubusercontent.com/736985/101647906-4747c500-3a07-11eb-956a-b48068e0cb4a.png">

**Comment by christocracy** [comment]
Ignore.  It's a bot use by Google when reviewing the app.  See [here](https://github.com/transistorsoft/react-native-background-fetch/issues/295)

Btw, this is not where to seek support.  You should post your issue to the appropriate repo for *Cordova*, *React Native* or *Flutter*.

**Comment by jacobg** [comment]
OK thanks!
