### ISSUE TITLE
Testing For Android 12

### ISSUE THREAD

**Issue by talibbk** [transistorsoft/transistor-background-fetch#12]
I am trying to test my app for upcoming Android 12.  
My build fails at :  
> Execution failed for task ':app:installDevDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl545282450.tmp/base.apk (at Binary XML file line #340): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present. 

I have fixed other similar errors by adding attribute android:exported to < activity > components that have < intent-filter > s declared in the app’s AndroidManifest.xml file, but i can't find solution for this one.
I am using react-native-background-geolocation which requires react-native-background-fetch as dependency.
I hope you can look into this.
Thankyou

**Comment by plat2eau** [comment]
experiencing the same problem

**Comment by plat2eau** [comment]
@talibbk were you able to find any workaround?

**Comment by christocracy** [comment]
[`BootReceiver with android:exported`](https://github.com/transistorsoft/transistor-background-fetch/blob/master/android/tsbackgroundfetch/src/main/AndroidManifest.xml#L11)

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.transistorsoft.tsbackgroundfetch">

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

    <application>
        <receiver android:name="com.transistorsoft.tsbackgroundfetch.FetchAlarmReceiver" />
        <service android:name="com.transistorsoft.tsbackgroundfetch.FetchJobService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true" />
        <receiver android:name="com.transistorsoft.tsbackgroundfetch.BootReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
    </application>
</manifest>
```
